---
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: "deploymentgreem"
spec: 
  replicas: 3
  selector:
    matchLabels:
      version: "v2"
  template:
    metadata:
      name: "mypod"
      labels:
        version: "v2"
    spec:
      containers:
      - name: "myos"
        image: jinny1/gfgflaskapp:v2

---

apiVersion: v1
kind: Service
metadata:
  name: "servicegreen"
spec:
  selector:
    version: "v2"
  ports:
  - port: 80
    targetPort: 80
  type: LoadBalancer
